### ISSUE TITLE
Error installing on ARM64 server

### ISSUE THREAD

**Issue by 4abhinavjain** [YunoHost-Apps/code-server_ynh#12]
Hi,

I am trying to install the code-server via webgui on a Debian 10 ARM64 server with 16GB RAM. The installation doesn't give any errors. However, the site give 502 and under Services, code-server fails with an error:

`systemd[1]: Started VS Code Server.
Feb 19 17:39:27 systemd[1]: code-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 19 17:39:27 systemd[1]: code-server.service: Failed with result 'exit-code'.`

Also the log says:
`/opt/yunohost/code-server/bin/code-server: 36: exec: /opt/yunohost/code-server/lib/node: Exec format error`

I suspect this is due to ARM64 instead of x86. Is that the case? Happy to provide more info if needed ( Yunohost: 4.3.6.2)

Thanks,

**Comment by Tagadda** [comment]
Hi, can you send the full install logs please ?

**Comment by 4abhinavjain** [comment]
Thanks, @Tagadda The install log seems ok https://paste.yunohost.org/raw/ezamexomed

Here is the services log and there it is failing- https://paste.yunohost.org/exovucufib

**Comment by Tagadda** [comment]
This should be fixed by the last update, there was a typo in the source file :grin:

**Comment by 4abhinavjain** [comment]
Thanks, Tagadda for the prompt fix.

**Comment by 4abhinavjain** [comment]
Bravo! I just tried the fix and can confirm it is working now.

Thanks again for the great work and kind instructions. I will skip 4.0.2 for now.
