### ISSUE TITLE
Couldn't upgrade 4.2.0 to 4.3.0 or install 4.3.0 after

### ISSUE THREAD

**Issue by Sekanato** [YunoHost-Apps/code-server_ynh#20]
### Describe the bug

On upgrade from 4.2.0 to 4.3.0 the app was deleted with "couldn't restore from backup" When tried to install again, the following happened – https://paste.yunohost.org/raw/gasubuxiya

### Context

- Hardware: Debian VPS on Linode
- YunoHost version: 4.3.6.3
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: modified delimiters for postfix in main.cf
- Using, or trying to install package version/branch: 4.3.0, from standard UI catalogue
- If upgrading, current package version: was 4.2.0, but uninstalled when upgrading

### Expected behavior

Successful upgrade or install.

**Comment by Tagadda** [comment]
This is weird. Do you still experience the issue ?
Can you share the content of `/etc/nginx/conf.d/ssowat.conf` ?

**Comment by Tagadda** [comment]
Closing. Feel free to reopen this if you experience the issue again.
