### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by SirSharanChakradhar** [YunoHost-Apps/code-server_ynh#26]
Unable to Install VSCODE server on YUNOHOST

### Context

- Hardware: * LINODE NANO*
- YunoHost version:  4.3.6.3 (stable).
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

Clicking general Install button on Yunohost

### Logs

https://paste.yunohost.org/raw/emoxukofoc

**Comment by Tagadda** [comment]
This app require a dedicated domain name.
As written in the log :
```
This URL is either unavailable, or conflicts with the already installed app(s):
 * maindomain.tld/phpsysinfo → PhpSysInfo (phpsysinfo)
 * maindomain.tld/mantis → Mantis (mantis)
 * maindomain.tld/monica → Monica (monica)
 * maindomain.tld/ihatemoney → I Hate Money (ihatemoney)
 * maindomain.tld/jupyterlab → JupyterLab (jupyterlab)
 * maindomain.tld/diagram → Diagrams.net (diagramsnet)
 * maindomain.tld/mindmaps → Mindmaps (mindmaps)
 * maindomain.tld/nodered/admin → Node-RED (nodered)
 * maindomain.tld/nodered → Node-RED (endpoints) (nodered)
 * maindomain.tld/nodered/ui → Node-RED (ui) (nodered)
 * maindomain.tld/nullboard → Nullboard (nullboard)
 * maindomain.tld/mymind → My Mind (my-mind)
 * maindomain.tld/kanboard → Kanboard (kanboard)
 * maindomain.tld/kanboard/jsonrpc.php → Kanboard (api) (kanboard)
 * maindomain.tld/nextcloud → Nextcloud (nextcloud)
```
You'll need to create a subdomain like `code.maindomain.tld` then install the app on this domain.
