### ISSUE TITLE
Installation Fails During Compilation

### ISSUE THREAD

**Issue by N-Upchurch** [YunoHost-Apps/code-server_ynh#3]
### Describe the bug

Installation fails during compilation. Compilation takes a very long time, eventually failing. Compilation takes significant system resources:

![image](https://user-images.githubusercontent.com/8893713/125974438-5c1cbae7-a427-42fc-92bd-af04ea627d8f.png)

### Context

- Hardware: VPS bought online: 2 cores, 4GB RAM
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH and through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Steps to reproduce

Attempt to install code-server

### Expected behavior
code-server installs successfully

### Logs
```
  YNH_APP_ID: code-server
  YNH_APP_INSTANCE_NAME: code-server
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 3.10.2~ynh2
error: An error occurred inside the app installation script
interface: api
operation: app_install
parent: null
related_to:
- - app
  - code-server
started_at: 2021-07-16 04:55:22.303419
success: false
yunohost_version: 4.2.6.1
```

**Comment by Jules-Bertholet** [comment]
VSCode is big and complex software, compiling it will take a long time and lots of resources. Add swap space if you run out of memory during install. Without logs, I cannot diagnose anything more

**Comment by N-Upchurch** [comment]
> VSCode is big and complex software, compiling it will take a long time and lots of resources. Add swap space if you run out of memory during install. Without logs, I cannot diagnose anything more

Ok thanks. I'll give that a try. What's curious is that I'm not running out of memory. Do you have any advice on how I could get more detailed logs?

**Comment by Jules-Bertholet** [comment]
You should be able to find them in the Web UI, or with `sudo yunohost log ...` commands
