### ISSUE TITLE
From Terminal, unable to use sudo (file system with the 'nosuid' option set)

### ISSUE THREAD

**Issue by pihomeserver** [YunoHost-Apps/code-server_ynh#63]
### Describe the bug

Unable to use sudo command within a terminal

### Context

- Hardware: : *VPS bought online*
- YunoHost version: 11.2.4
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - Using some containers
- Using, or trying to install package version/branch: latest available from Yunohost app store

### Steps to reproduce

- Fresh install of the app
- Access it
- Run a terminal
- Execute sudo ls command

### Logs

![269930257-363bb638-4cb0-42f0-bdeb-3263ec6835ed](https://github.com/YunoHost-Apps/code-server_ynh/assets/3817578/67ef795b-a2cf-4e39-ac85-ba32acfc3c31)

Any idea how to configure in order to get an access to the command or if it's a feature for any security reason ?

**Comment by Tagadda** [comment]
This is for security reason.
The code-server service is sandboxed and can't get new privileges.
