### ISSUE TITLE
After update failed to start

### ISSUE THREAD

**Issue by stepcellwolf** [YunoHost-Apps/code-server_ynh#92]
### Describe the bug

After upgrading to latest version of code-server is failing to start. see details bellow. 

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.11.3 (stable)
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- code-server version: 4.89.1~ynh1
### Steps to reproduce

- After upgrading to latest version code-server can not start, please see logs below.

### Expected behavior

It should work without any problems no env settings have been changed.

### Logs

``
-- Journal begins at Sat 2024-05-04 12:52:18 UTC, ends at Fri 2024-05-17 08:44:47 UTC. --
May 16 14:21:46 systemd[1]: Stopping VS Code Server...
May 16 14:21:46 systemd[1]: code-server.service: Succeeded.
May 16 14:21:46 systemd[1]: Stopped VS Code Server.
May 16 14:21:46 systemd[1]: code-server.service: Consumed 27.814s CPU time.
May 16 14:21:53 systemd[1]: Started VS Code Server.
May 16 14:21:53 systemd[1]: code-server.service: Main process exited, code=exited, status=1/FAILURE
May 16 14:21:53 systemd[1]: code-server.service: Failed with result 'exit-code'.
May 17 08:43:50 systemd[1]: Started VS Code Server.
May 17 08:43:50 systemd[1]: code-server.service: Main process exited, code=exited, status=1/FAILURE
May 17 08:43:50 systemd[1]: code-server.service: Failed with result 'exit-code'.
May 17 08:43:55 systemd[1]: Started VS Code Server.
May 17 08:43:55 systemd[1]: code-server.service: Main process exited, code=exited, status=1/FAILURE
May 17 08:43:55 systemd[1]: code-server.service: Failed with result 'exit-code'.
May 17 08:44:01 systemd[1]: Started VS Code Server.
May 17 08:44:02 systemd[1]: code-server.service: Main process exited, code=exited, status=1/FAILURE
May 17 08:44:02 systemd[1]: code-server.service: Failed with result 'exit-code'.
``

**Comment by Tagadda** [comment]
Should by fixed by last release.
